from enum import Enum


class QueryType(Enum):
    START_GAME = "start_game"
    JOIN_GAME = "join_game"
    RUN = "run"
    TERMINATE = "terminate"
    ALIVE = "alive"
    DESCRIPTION = "description"
    ROLES = "roles"
    NOMINATED = "nominated"
    VOTED = "voted"
    STATUS = "status"
    SPEECH = "speech"
    END_SPEECH = "end_speech"
    PRE_NOMINATE = "pre_nominate"
    NOMINATE = "nominate"
    PRE_VOTE = "pre_vote"
    VOTE = "vote"
    PRE_BALANCE = "pre_balance"
    BALANCE = "balance"
    START_NIGHT = "start_night"
    SKIP_NIGHT = "skip_night"
    NIGHT_ACTION = "night_action"
    MAFIA_CHAT = "mafia_chat"
